services:
  microbin:
    image: danielszabo99/microbin:latest
    container_name: microbin
    restart: always
    ports:
      - "65525:8080"
    volumes:
      - ./microbin-data:/app/microbin_data
    environment:
      # MICROBIN_BASIC_AUTH_USERNAME: ${MICROBIN_BASIC_AUTH_USERNAME}
      # MICROBIN_BASIC_AUTH_PASSWORD: ${MICROBIN_BASIC_AUTH_PASSWORD}
      MICROBIN_ADMIN_USERNAME: admin
      MICROBIN_ADMIN_PASSWORD: <secret>
      MICROBIN_EDITABLE: true
      # MICROBIN_FOOTER_TEXT: ${MICROBIN_FOOTER_TEXT}
      MICROBIN_HIDE_FOOTER: true
      MICROBIN_HIDE_HEADER: false
      MICROBIN_HIDE_LOGO: true
      MICROBIN_NO_LISTING: false
      MICROBIN_HIGHLIGHTSYNTAX: true
      # MICROBIN_BIND: ${MICROBIN_BIND}
      # MICROBIN_PRIVATE: ${MICROBIN_PRIVATE}
      # MICROBIN_PURE_HTML: ${MICROBIN_PURE_HTML}
      # MICROBIN_DATA_DIR: ${MICROBIN_DATA_DIR}
      # MICROBIN_JSON_DB: ${MICROBIN_JSON_DB}
      # MICROBIN_PUBLIC_PATH: ${MICROBIN_PUBLIC_PATH}
      # MICROBIN_SHORT_PATH: ${MICROBIN_SHORT_PATH}
      # MICROBIN_READONLY: ${MICROBIN_READONLY}
      # MICROBIN_SHOW_READ_STATS: ${MICROBIN_SHOW_READ_STATS}
      # MICROBIN_TITLE: ${MICROBIN_TITLE}
      # MICROBIN_THREADS: ${MICROBIN_THREADS}
      # MICROBIN_GC_DAYS: ${MICROBIN_GC_DAYS}
      # MICROBIN_ENABLE_BURN_AFTER: ${MICROBIN_ENABLE_BURN_AFTER}
      # MICROBIN_DEFAULT_BURN_AFTER: ${MICROBIN_DEFAULT_BURN_AFTER}
      MICROBIN_WIDE: true
      # MICROBIN_QR: ${MICROBIN_QR}
      # MICROBIN_ETERNAL_PASTA: ${MICROBIN_ETERNAL_PASTA}
      # MICROBIN_ENABLE_READONLY: ${MICROBIN_ENABLE_READONLY}
      # MICROBIN_DEFAULT_EXPIRY: ${MICROBIN_DEFAULT_EXPIRY}
      # MICROBIN_NO_FILE_UPLOAD: ${MICROBIN_NO_FILE_UPLOAD}
      # MICROBIN_CUSTOM_CSS: ${MICROBIN_CUSTOM_CSS}
      # MICROBIN_HASH_IDS: ${MICROBIN_HASH_IDS}
      MICROBIN_ENCRYPTION_CLIENT_SIDE: true
      MICROBIN_ENCRYPTION_SERVER_SIDE: true
      MICROBIN_MAX_FILE_SIZE_ENCRYPTED_MB: 16
      MICROBIN_MAX_FILE_SIZE_UNENCRYPTED_MB: 16
