services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "65523:8000"
      - "65522:9443" # HTTPS
      - "65521:9000" # HTTP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  portainer_data:
