# services:
#   sing-box:
#     image: ghcr.io/sagernet/sing-box
#     container_name: sing-box
#     network_mode: host
#     privileged: true
#     volumes:
#       - ./:/etc/sing-box/
#     command: -c /etc/sing-box/config.client.json run

services:
  sing-box:
    image: ghcr.io/sagernet/sing-box
    container_name: sing-box
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./:/etc/sing-box/
    command: -c /etc/sing-box/config.json run
    restart: always
